server:
  port: 8080
  servlet:
    context-path: /dreams-blog

spring:
  profiles:
    include: datasource

  mvc:
    static-path-pattern: /resource/**
  resources:
    static-locations: ["classpath:/META-INF/resources/", "classpath:/resources/","classpath:/static/", "classpath:/public/"]

  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    content-type: text/html
    template-loader-path: "classpath:/templates/"
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
