mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.springboot.webconfig.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
